ColmanWebProject2021/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ColmanWebProject2021.Data;
using ColmanWebProject2021.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace ColmanWebProject2021.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ColmanWebProject2021Context _context;
        private readonly UserManager<User> _userManager;

        public OrdersController(ColmanWebProject2021Context context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Orders
        [Authorize]
        public async Task<IActionResult> Index(string restaurantName, DateTime fromDate, DateTime toDate)
        {
            IQueryable<Order> orders = _context.Order.Include(o => o.Restaurant);

            // Build the where clause according to the filter parameters:
            // Check is the restaurantName filter was filled
            if (!String.IsNullOrEmpty(restaurantName))
            {
                orders = orders.Where(o => o.Restaurant.Name.Contains(restaurantName));
            }

            // Check if the fromDate filter was filled
            if (fromDate != DateTime.MinValue)
            {
                orders = orders.Where(o => o.DateTime.Date >= fromDate.Date);
            }

            // Check if the toDate filter was filled
            if (toDate != DateTime.MinValue)
            {
                orders = orders.Where(o => o.DateTime.Date <= toDate);
            }

            // Check if the user isn't an admin.
            if (!User.IsInRole("Admin"))
            {

                // Get the connected user.
                User user = await _userManager.GetUserAsync(HttpContext.User);

                // Get only orders that belong to the connected user.
                orders = orders.Where(o => o.CustomerId == user.Id);
            }

            List<Order> list = await orders.ToListAsync();

            return View(list);
        }

        public async Task<IActionResult> Search(string restaurantName, DateTime fromDate, DateTime toDate)
        {
            IQueryable<Order> orders = _context.Order.Include(o => o.Restaurant);

            // Build the where clause according to the filter parameters:
            // Check is the restaurantName filter was filled
            if (!String.IsNullOrEmpty(restaurantName))
            {
                orders = orders.Where(o => o.Restaurant.Name.Contains(restaurantName));
            }

            // Check if the fromDate filter was filled
            if (fromDate != DateTime.MinValue)
            {
                orders = orders.Where(o => o.DateTime.Date >= fromDate.Date);
            }

            // Check if the toDate filter was filled
            if (toDate != DateTime.MinValue)
            {
                orders = orders.Where(o => o.DateTime.Date <= toDate);
            }

            // Check if the user isn't an admin.
            if (!User.IsInRole("Admin"))
            {

                // Get the connected user.
                User user = await _userManager.GetUserAsync(HttpContext.User);

                // Get only order that belong to the connected user.
                orders = orders.Where(o => o.CustomerId == user.Id);
            }

            List<Order> list = orders.ToList();

            return PartialView("List", list);
        }

        // GET: Orders/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            var order = await _context.Order
                .Include(o => o.Customer)
                .Include(o => o.Restaurant)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            // Get the connected user.
            User user = await _userManager.GetUserAsync(HttpContext.User);

            if (!User.IsInRole("Admin") && !user.Id.Equals(order.CustomerId))
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            return View(order);
        }

        // GET: Orders/Create
        [Authorize]
        public async Task<IActionResult> Create(string? restaurantId)
        {
            Restaurant restaurant = null;

            // Check if the id field is filled and valid, and if so, hide the restaurant field.
            if (!string.IsNullOrEmpty(restaurantId))
            {
                TempData["restaurantId"] = restaurantId;
                int id = Int32.Parse(restaurantId);
                restaurant = await _context.Restaurant.FirstOrDefaultAsync(r => r.Id == id);

                if (restaurant != null)
                {
                    ViewData["TitleAddition"] = "for " + restaurant.Name;
                }
            }

            ViewBag.showRestaurants = (restaurant == null);
            TempData["showRestaurants"] = ViewBag.showRestaurants;
            
            PopulateRestaurantsDropDownList();
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,RestaurantId,DateTime,Comments,NumberOfSeats")] Order order)
        {
            if (ModelState.IsValid)
            {
                // Get the connected user.
                User user = await _userManager.GetUserAsync(HttpContext.User);
                order.Customer = user;

                // If the restaurant was already selected beforehand - add it here.
                if (!(bool)TempData["showRestaurants"])
                    order.RestaurantId = Int32.Parse(TempData["restaurantId"] as string);

                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }
            
            var order = await _context.Order.Include(o => o.Customer).FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            // Get the connected user.
            User user = await _userManager.GetUserAsync(HttpContext.User);

            if (!User.IsInRole("Admin") && !user.Id.Equals(order.CustomerId))
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            PopulateRestaurantsDropDownList();
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RestaurantId,DateTime,Comments,NumberOfSeats")] Order order)
        {
            if (id != order.Id)
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    order.Customer = await _userManager.GetUserAsync(HttpContext.User);
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return new NotFoundViewResult("NotFoundError", "Order was not found");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            var order = await _context.Order
                .Include(o => o.Restaurant)
                .Include(o => o.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (order == null)
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            // Get the connected user.
            User user = await _userManager.GetUserAsync(HttpContext.User);

            if (!User.IsInRole("Admin") && !user.Id.Equals(order.CustomerId))
            {
                return new NotFoundViewResult("NotFoundError", "Order was not found");
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

ColmanWebProject2021/Controllers/RestaurantTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ColmanWebProject2021.Data;
using ColmanWebProject2021.Models;
using Microsoft.AspNetCore.Http;

namespace ColmanWebProject2021.Controllers
{
    public class RestaurantTypesController : Controller
    {
        private readonly ColmanWebProject2021Context _context;

        public RestaurantTypesController(ColmanWebProject2021Context context)
        {
            _context = context;
        }

        // GET: RestaurantTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.RestaurantType.ToListAsync());
        }

        // GET: RestaurantTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @restaurantType = await _context.RestaurantType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@restaurantType == null)
            {
                return NotFound();
            }

            HttpContext.Session.SetString("restaurantTypeId", restaurantType.Id.ToString());
            HttpContext.Session.SetString("restaurantTypeName", restaurantType.Name);

            return View(restaurantType);
        }

        // GET: RestaurantTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RestaurantTypes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] RestaurantType restaurantType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(restaurantType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(restaurantType);
        }

        // GET: RestaurantTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurantType = await _context.RestaurantType.FindAsync(id);
            if (restaurantType == null)
            {
                return NotFound();
            }
            return View(restaurantType);
        }

        // POST: RestaurantTypes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] RestaurantType restaurantType)
        {
            if (id != restaurantType.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(restaurantType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantTypeExists(restaurantType.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(restaurantType);
        }

        // GET: RestaurantTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurantType = await _context.RestaurantType
                .FirstOrDefaultAsync(m => m.Id == id);
            if (restaurantType == null)
            {
                return NotFound();
            }

            return View(restaurantType);
        }

        // POST: RestaurantTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restaurantType = await _context.RestaurantType.FindAsync(id);
            _context.RestaurantType.Remove(restaurantType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantTypeExists(int id)
        {
            return _context.RestaurantType.Any(e => e.Id == id);
        }

        public IActionResult GetRestaurantTypesDetails()
        {
            int restaurantTypesId = Int32.Parse(HttpContext.Session.GetString("restaurantTypeId"));

            int numOfRestaurants = (from restaurant in _context.Restaurant
                             where restaurant.Type.Id == restaurantTypesId
                             select restaurant.Type.Id).Distinct().Count();

            int numOfOrders = (from type in _context.RestaurantType
                                join restaurant in _context.Restaurant
                                on type.Id equals restaurant.Type.Id
                                join order in _context.Order
                                on restaurant.Id equals order.Restaurant.Id
                                where type.Id == restaurantTypesId
                               select type.Id).Count();

            return Json(new { numofrestaurants = numOfRestaurants, numoforders= numOfOrders });
        }

        [HttpPost]
        public ActionResult NavToRestaurants()
        {
            HttpContext.Session.SetString("restaurantTypeName", HttpContext.Session.GetString("restaurantTypeName"));
            HttpContext.Session.SetString("navigatedFrom", "RestaurantType");
            return Json(Url.Action("Index", "Restaurants"));
        }

        public IActionResult Search(string restaurantTypeName, string restuarantTypeDescription)
        {
            ViewBag.typeName = "";
            var restaurantTypes = from RestaurantType in _context.RestaurantType
                        select RestaurantType;
            restaurantTypes = restaurantTypes.OrderBy(r => r.Name);

            if (!String.IsNullOrEmpty(restaurantTypeName))
                restaurantTypes = restaurantTypes.Where(r => r.Name.ToUpper().Contains(restaurantTypeName.ToUpper()));

            if (!String.IsNullOrEmpty(restuarantTypeDescription))
                restaurantTypes = restaurantTypes.Where(r => r.Description.ToUpper().Contains(restuarantTypeDescription.ToUpper()));

            if (restaurantTypes.Count() > 0)
                return PartialView("List", restaurantTypes.ToList());
            else return PartialView("List", new List<ColmanWebProject2021.Models.RestaurantType>());
        }



    }
}

ColmanWebProject2021/Views/Restaurants/Admin.cshtml
@*@if (User.Identity.IsAuthenticated)
    {
        @if (User.IsInRole("Admin"))
        {*@
<div class="row" style="display: flex;">
    <div class="text-center stat-card col-md-6">
        <h2 class="ma-2">Top Restaurants</h2>
        <div id="top-restaurants-chart"></div>
    </div>
</div>
<div class="row" style="display: flex;">
    <div class="text-center stat-card">
        <div class="form-group col">
            <label class="control-label">Month : </label>
            <select id="month" class="form-control" onchange="updateData()" style="width: 10rem"></select>
        </div>
        <div id="avg-seats-per-restaurant"></div>
    </div>
</div>

@*}
    }*@

@section Scripts {
    <script src="~/js/app.js"></script>
    
    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
    {
        <script type="text/javascript">
            $.ajax({
                url: "/Restaurants/MostPopularRestaurants",
                context: document.body
            }).done(function (data) {
                create_pie_chart(data, "#top-restaurants-chart");
            });

            updateData = () => {
                var selectMonth = $('#month').find(":selected")[0].value;

                $.ajax({
                    url: "/Restaurants/AvrageNumberOfSeatsPerRestaurantInMonth?month=" + selectMonth,
                    context: document.body
                }).done(function (data) {
                    create_bar_chart(data, "#avg-seats-per-restaurant");
                });
            };

            initSelect = () => {
                var selectBox = document.getElementById('month');
                var months = [{ value: 1, text: "January" },
                    { value: 2, text: "February" },
                    { value: 3, text: "March" },
                    { value: 4, text: "April" },
                    { value: 5, text: "May" },
                    { value: 6, text: "June" },
                    { value: 7, text: "July" },
                    { value: 8, text: "August" },
                    { value: 9, text: "September" },
                    { value: 10, text: "October" },
                    { value: 11, text: "November" },
                    { value: 12, text: "December" }];

                for (var i = 0, l = months.length; i < l; i++) {
                    var option = months[i];
                    selectBox.options.add(new Option(option.text, option.value, option.value == 1));
                }

                updateData();
            };
            initSelect();
        </script>
    }
}

ColmanWebProject2021/Views/Restaurants/Create.cshtml
@model ColmanWebProject2021.Models.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create new restaurant</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group space-above-input-row">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group space-above-input-row">
                <label asp-for="Type.Name" class="control-label">Reasturant type</label>
                <select id="restaurantTypeName" name="Type.Name" class="form-control"></select>
            </div>
            <div class="form-group space-above-input-row">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group space-above-input-row">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group space-above-input-row">
                <label asp-for="GuestCapacity" class="control-label"></label>
                <input asp-for="GuestCapacity" class="form-control" />
                <span asp-validation-for="GuestCapacity" class="text-danger"></span>
            </div>
            <div class="form-group space-above-input-row form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Accessible" /> @Html.DisplayNameFor(model => model.Accessible)
                </label>
            </div>
            <div class="form-group space-above-input-row form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Kosher" /> @Html.DisplayNameFor(model => model.Kosher)
                </label>
            </div>
            <div class="form-group space-above-input-row">
                <label asp-for="OpeningTime" class="control-label"></label>
                <input asp-for="OpeningTime" class="form-control" />
                <span asp-validation-for="OpeningTime" class="text-danger"></span>
            </div>
            <div class="form-group space-above-input-row">
                <label asp-for="ClosingTime" class="control-label"></label>
                <input asp-for="ClosingTime" class="form-control" />
                <span asp-validation-for="ClosingTime" class="text-danger"></span>
            </div>
            <div class="form-group space-above-input-row">
                <label asp-for="ImgUrl" class="control-label"></label>
                <input asp-for="ImgUrl" class="form-control" />
                <span asp-validation-for="ImgUrl" class="text-danger"></span>
            </div>
            <div class="form-group space-above-input-row">
                <a asp-action="Index" class="btn btn-light"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>
                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-disk"></span> Save</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var url = "/Restaurants/GetRestaurantTypes"
        var select = document.getElementById("restaurantTypeName")
        $.ajax({
            type: 'GET',
            url: url,
            contentType: 'json',
            success: function (types) {

                for (var i = 0; i < types.length; i++) {
                    var option = document.createElement("option");
                    option.text = types[i].name;
                    select.add(option);
                }
            }
        })</script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ColmanWebProject2021/Views/Restaurants/Details.cshtml
@model ColmanWebProject2021.Models.Restaurant

@{ ViewData["Title"] = "Details"; }

<div class="restaurant-display">
    <h1>@Model.Name</h1>
    <div>
        <hr />
        <div class="row">
            <div class="room-card new" onclick="location.href='@Url.Action("Create","Orders", new { restaurantId=@Model.Id })'">
                <h4>
                    Book a place <span class="glyphicon glyphicon-plus"></span>
                </h4>
            </div>

            <div class="col-sm-12" style="cursor: auto;">
                @if (@Model.ImgUrl != "")
                {
                    <img src=@Model.ImgUrl style="  max-width: 220px;
                                                    max-height: 220px;
                                                    border-radius: 20px;
                                                    margin-top: 1rem;
                                                    margin-bottom: 1rem;">}
                <h3>@Model.Description</h3>
                <div class="row restaurants-container">
                    <div class="col-md-12 typetag" onclick="location.href='@Url.Action("Details","RestaurantTypes", new { id = @Model.Type.Id })'" style="cursor:pointer">
                        @Model.Type.Name
                    </div>
                </div>
                <div class="row restaurants-container">
                    <div class="col-md-4 detailstag">
                        @if (Model.Kosher)
                        {<div>Kosher</div> }
                        else
                        { <div>Not kosher</div>}
                    </div>
                    <div class="col-md-4 detailstag">
                        @if (Model.Accessible)
                        {<div>Accessible</div> }
                        else
                        { <div>Not accessible</div>}
                    </div>
                </div>
                <div class="row restaurants-container">
                    <div class="col-md-6 detailstag" style="width: 250px;">
                        Up to @Model.GuestCapacity people
                    </div>
                </div>
                <div class="row restaurants-container">
                    <div class="col-md-6 detailstag" style="width: 250px;">
                        Opening hour: @Model.OpeningTime.ToShortTimeString()
                    </div>

                    <div class="col-md-6 detailstag" style="width: 250px;">
                        Closing hour: @Model.ClosingTime.ToShortTimeString()
                    </div>
                </div>
                <center>
                    <div id="myMap" style="width:400px;height:300px;" />
                </center>
            </div>
        </div>
    </div>
    <div style="padding-top:2rem; cursor: auto;">
        <a asp-action="Index" class="btn btn-light"><span class="glyphicon glyphicon-chevron-left"></span> Back</a>

        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
        {
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
            <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete</a>
        }                     
    </div>
</div>


<script type="text/javascript">
    var map;
    var searchManager;

    function GetMap() {
        map = new Microsoft.Maps.Map("#myMap");
        addRestaurantToMap('@Model.Name', '@Model.Address');

    }

    function addRestaurantToMap(name, address) {
        findLocationByAddress(address, function (location) {
            var restaurantLocation = location;
            var restaurantPoint = new Microsoft.Maps.Pushpin(restaurantLocation);
            var infobox = new Microsoft.Maps.Infobox(restaurantLocation, {
                title: name,
                description: address,
                visible: false
            });
            infobox.setMap(map);
            infobox.setOptions({ visible: true });
            Microsoft.Maps.Events.addHandler(restaurantPoint, 'click', function () {
                infobox.setOptions({ visible: true });
            });
            map.entities.push(restaurantPoint);
            map.setView({
                center: location,
                zoom: 15
            });
        });
    }

    function findLocationByAddress(address, func) {
        // If search manager is not defined, load the search module
        if (!searchManager) {
            // Create an instance of the search manager and re-enter function
            Microsoft.Maps.loadModule('Microsoft.Maps.Search', function () {
                searchManager = new Microsoft.Maps.Search.SearchManager(map);
                findLocationByAddress(address, func);
            });
        } else {
            var searchRequest = {
                where: address,
                callback: function (r) {
                    func(r.results[0].location);
                },
                errorCallback: function (e) {
                    // If there is an error
                    console.log("No results found for this address: " + address);
                }
            };

            // Make the geocode request
            searchManager.geocode(searchRequest);
        }
    }
</script>
<script type="text/javascript" src="https://www.bing.com/api/maps/mapcontrol?callback=GetMap&key=AmTbZrbvXwVy0XO22GneszL2g9TZqn9gsLSs8ejbQe-EIb5_QvppPlAyyD_59HII" async defer></script>

ColmanWebProject2021/Views/Restaurants/Index.cshtml
@model IEnumerable<ColmanWebProject2021.Models.Restaurant>

@{ ViewData["Title"] = "Our restaurnats"; }

<center>
    <h1>Our restaurnats</h1>
</center>

<div class="row">
    <div class="search-card container">
        <form id="searchForm" class="form-inline filter row">
            <div class="form-group col">
                <label class="control-label" for="restaurantName"><b>Restaurant name : </b></label>
                <input id="nameForm" class="form-control" type="text" name="restaurantName">
            </div>
            <div class="form-group col">
                <input type="hidden" id="type_name" value="@ViewBag.typeName" />
                <label class="control-label" for="typeName"><b>Restaurant type : </b></label>
                <select class="form-control" id="restaurantTypeName" name="typeName">
                    <option value="">All</option>
                </select>
            </div>
            <div class="form-group col">
                <label class="control-label" for="accessibility"><b>Accessibility : </b></label>
                <select class="form-control" id="accessibility" name="accessibility">
                    <option value="">Any</option>
                    <option value="true">Accessible</option>
                    <option value="false">Not Accessible</option>
                </select>
            </div>
        </form>
    </div>
</div>
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div class="row">

        <div onclick="location.href='@Url.Action("Create")'" class="room-card new">
            <h4>
                Add new restaurant
                <span class="glyphicon glyphicon-plus" />
            </h4>
        </div>
    </div>
}
<div id="restaurantsList">
</div>

@section Scripts {
    <script src="~/js/restaurantsList.js"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}